dist: focal
language: ruby
cache: bundler
gemfile: Gemfile
addons:
  apt:
    packages:
      - graphicsmagick
      - webp
script:
  - JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: main
branches:
  only:
    - main
rvm:
  - 2.4